---
# LDAP user create config

base: dc=example,dc=com
user: (uid=%s)  # user filter
group: (uniqueMember=uid=%s,ou=people,dc=example,dc=com) # group filter
host: localhost
port: 10389
binddn: uid=admin,ou=system
bindpwd: secret
dn: uid=%s,ou=people,dc=example,dc=com
password: bar
attributes: sn,uid,cn,homePhone